version: '3'

services:
    postgres:
        image: postgres:latest
        container_name: fsw-v3-postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            PGDATA: /data/postgres
        ports:
            - '5432:5432'
        volumes:
            - ./data/pg:/data/postgres
